### PR TITLE
update mnconvert dependency to avoid conflict on metanorma-cli

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-cli#261

### Metanorma PR checklist

 - NO Breaking changes (list related PRs)
 - NO Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - NO External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - NO Gem with native library introduced

### Depends on PRs

 - https://github.com/metanorma/mnconvert-ruby/pull/2

### Related PRs

 - https://github.com/metanorma/mnconvert-ruby/pull/2
 - https://github.com/metanorma/metanorma-cli/pull/262

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@CAMOBAP we will have to apply this to all flavors that use MnConvert.

**Comment by CAMOBAP** [comment]
> we will have to apply this to all flavors that use MnConvert.

Yep, but I didn't find other invocation on MnCovert in other `metanorma-cli` deps. @ronaldtse maybe you know which ones are missing?

**Comment by CAMOBAP** [comment]
@reviewers Also actual version in gemspec will be changed after release of mnconvert

**Comment by ronaldtse** [comment]
> Yep, but I didn't find other invocation on MnCovert in other `metanorma-cli` deps. @ronaldtse maybe you know which ones are missing?

Then there are none -- ISOSTS and NISO STS only apply to ISO and IEC flavors. And metanorma-iec inherits from metanorma-iso. Let's go with this!

**Review by ronaldtse — APPROVED** [review]

**Comment by CAMOBAP** [comment]
Ready for review, test https://github.com/metanorma/metanorma-iso/blob/main/spec/asciidoctor/refs_spec.rb#L6 is broken

**Pull request merged**
