### PR TITLE
Copyright historical

### PR DESCRIPTION
**Pull request by Intelligent2013**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Review by opoudjis — COMMENTED** [review]
I don't understand your use of span:std_docNumber for copyright year; canonically it should be span:date, and the Word span style would be stddocNumber and stdpublisher. If you're intending Word compatibility, please use those instead.

**Comment by Intelligent2013** [comment]
> I don't understand your use of span:std_docNumber for copyright year; canonically it should be span:date, and the Word span style would be stddocNumber and stdpublisher. If you're intending Word compatibility, please use those instead.

@opoudjis I've just copy-past this fragment from the current https://github.com/metanorma/metanorma-iso/blob/main/lib/metanorma/iso/boilerplate.adoc?plain=1:
```xml
[[boilerplate-year]]
&#xa9; span:std_publisher[{{ agency }}&#xa0;]span:std_docNumber[{{ docyear }}]
```

**Comment by Intelligent2013** [comment]
`span:std_docNumber` replaced by `span:date`.

**Comment by opoudjis** [comment]
I'm having difficulty working out why I marked it up that way, but it was wrong. Thank you!

**Pull request merged**
