### PR TITLE
Bugfix/no install fonts spec

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #476

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis @abunashir  @w00lf @andrew2net 

Last few weeks I worked to make specs executed inside the temp directory (mostly for metanorma processors).

Here is my observation which I would like to discuss:
 - We use large XML snippets a lot. In my understanding in most cases, this can be covered by few XPath checks so I propose to use XPath for any new tests
 - Usage of XPath will allow any developer who is new to the project easy to understand the proposal of the test (it will be very clear which part of XML checked)
 - XPath also suitable for checking a complex hierarchy

Let me know how do you think about it?

**Comment by andrew2net** [comment]
@CAMOBAP I use files instead of Heredoc in tests code. For example:
```
result = RelatonIso::IsoBibliography.get("ISO 19115", nil, lang: "en").to_xml
file = "spec/fixtures/iso_19115_en.xml"
File.write file, result, encoding: "UTF-8" unless File.exist? file
expect(result).to be_equivalent_to File.read(file, encoding: "UTF-8")
  .gsub(/(?<=<fetched>)\d{4}-\d{2}-\d{2}/, Date.today.to_s)
```

**Comment by CAMOBAP** [comment]
@andrew2net thanks for the response, for input files, I can agree with you, but do we really need the whole output file to make sure the logic works correctly? How do you think?

**Comment by andrew2net** [comment]
@CAMOBAP in some cases we need to check the whole output. For example for data model testing. But in case we need to test certain logic I agree with you. I don't like the large snippets either.

**Comment by opoudjis** [comment]
I do like the large snippets because there is a lot to track; I admit not everything needs to be a large snippet, particularly in the flavours as opposed to the two base gems. Is there a performance downside to the large snippets?

**Comment by CAMOBAP** [comment]
> Is there a performance downside to the large snippets?

@opoudjis nope, I didn't notice significant performance degradation. My point is more about readability, it's much easier to understand the purpose of the test (what exactly it checks)

For example https://github.com/metanorma/metanorma-iso/blob/master/spec/asciidoctor-iso/amd_spec.rb#L6-L129 .

In my opinion, we can replace large XML snippet with:
 - `count(/*/sections/*/clause) == X` - check total clause count
 - `/*/clause/clause/clause[title/text() == 'Term2'] - not nil` - check that specific nested `clause` exists
 - `/*/annex/appendix[title/text() == 'Appendix 1']` - not nil` - check specific node again

So instead of a large XML snippet 60 lines, we will have 3-6 lines with XPath check, a single XPath can validate deep hierarchy

**Comment by w00lf** [comment]
> > Is there a performance downside to the large snippets?
> 
> @opoudjis nope, I didn't notice significant performance degradation. My point is more about readability, it's much easier to understand the purpose of the test (what exactly it checks)
> 
> For example https://github.com/metanorma/metanorma-iso/blob/master/spec/asciidoctor-iso/amd_spec.rb#L6-L129 .
> 
> In my opinion, we can replace large XML snippet with:
> 
> * `count(/*/sections/*/clause) == X` - check total clause count
> * `/*/clause/clause/clause[title/text() == 'Term2'] - not nil` - check that specific nested `clause` exists
> * `/*/annex/appendix[title/text() == 'Appendix 1']` - not nil` - check specific node again
> 
> So instead of a large XML snippet 60 lines, we will have 3-6 lines with XPath check, a single XPath can validate deep hierarchy

Looks good to me, current test are quite cumbersome and difficult to read and sometimes there are just a couple of checks.

**Pull request merged**
