### PR TITLE
metanorma/metanorma-cli#273 do samples/templates testing on site

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-cli#273

### CODE REVIEW

**Comment by opoudjis** [comment]
This is failing, so I can't merge it @CAMOBAP

**Comment by CAMOBAP** [comment]
@opoudjis yep, I will move it to draft, sorry for confusion

**Comment by CAMOBAP** [comment]
@ronaldtse based onhttps://github.com/metanorma/metanorma-cli/pull/295#issuecomment-1415285229  and https://github.com/metanorma/metanorma-cli/pull/295#issuecomment-1420750690 I have implemented templates, samples testing on all OS/ruby versions

It takes more time than usual because missing cache for ruby-setup, but once we got merged it will still take few hours to run 1-3h. And release will happen after it

Should we go with these matrices or cut/optimize them?

**Comment by ronaldtse** [comment]
@CAMOBAP I am fine with the current setup. Any thoughts @opoudjis ?

**Comment by CAMOBAP** [comment]
@ronaldtse for now in the matrix we have 2.7, 3.0, 3.1, 3.2 (experimental)

Maybe we can skip 3.0?

@opoudjis I would like to get your feedback too because I will apply this workflow to all `metanorma-*` repos

**Comment by ronaldtse** [comment]
We could skip 3.0 for the final release since we already test it in the gems.

**Comment by opoudjis** [comment]
In fact, @CAMOBAP, which is needed is some sort of automated cascade of releases, because of the time lag:

* I will release the utility gems outside the cascade: because they are dependencies, they need to release outside the fortnightly cycle
* The cascade is: isodoc, then metanorma, then metanorma-standoc, then the flavours as shown above
 * isodoc, metanorma, metanorma-standoc are direct dependencies for each other. Standoc processing can only initiate once isodoc is released, and the gem is available to standoc. (Metanorma gem circular dependency is very rarely an issue, and if it becomes one, I will be manually releasing it.)
 * Similarly, iso can only release once standoc is released and available; iec once iso is available
 * ... But all that needs a script your side.
* And this will still prove unworkable, because GHA is monstrously unreliable, and fails for all sorts of reasons (as you know very well, @CAMOBAP, because you're who I complain about it to). But without some sort of automated release schedule, it will be so unworkable that I simply won't do it...

**Comment by opoudjis** [comment]
> > Test each gem locally, because that's how I identify and propagate changes resulting from dependencies of gems. 
> Does it mean that only one OS was covered during local testing, docker also tests only Linux. How does this protect us from issues on other platforms?

It does mean only one OS is covered, and the entire point of the remote testing is to discover the issues on other platforms. That's how it is already, and that's how it's going to remain. I only program in one platform, so this is not a new issue.

> > ....When I have concluded going through all the gems, check their status on GHA. 
> To be on the same page, what exactly are you checking just that test passing or anything else?

Yes, just that. Again, that's all I do now.

> > Remote testing such as you are proposing is going to take tens of minutes of dead time during which I am waiting idly for things to be resolved
> You mean the time that you need to wait between one gem release in progress and starting a release of the next gem, right? Ideally, we have a ticket that can address this [metanorma/metanorma-release#21](https://github.com/metanorma/metanorma-release/issues/21)

Yes, in cases of direct dependency, I expect the released gem to be available IMMEDIATELY; that is the case for html2doc > isodoc, isodoc > metanorma > metanorma-standoc. Even with delayed dependency, I am very worried that metanorma-iso might not be online by the time I come to release metanorma-iec. But if all the releasing is done by a remote script, at least I'm not left waiting around.

> From your perspective, it will look like a workflow where each job will responsible for the release of a particular gem. Dependencies between these jobs will the same as you listed in the comment above. So you will not have to wait to start next release, workflow will do it

So, to understand:

* I hit release of html2doc
* I compile html2doc locally <== I still have to do that, because the dependencies have to be tested for locally
* I start debugging of isodoc
* I hit release of isodoc
* If html2doc testing is still running, isodoc testing and release process will wait until the updated version of html2doc is available
* And the remote isodoc test will know that an html2doc job is underway or has failed, as opposed to me deciding not to release a new version of html2doc this fortnight

... You understand why I'm hesitating: there are a lot of moving parts.

> > This update is apparently going to introduce a whole lot of remote testing dead time between release of individual flavours, as templates and samples are tested in each successively.
> Unfortunatelly yes, but on another side, it will keep it more stable and safe.

Yes. That's all true. And I reiterate, if this ends up meaning that a release is spread over three days, or that I have to wait until 3 AM for a release to finish processing, then I will refuse to be involved in releases at all. That's why I'm offering the option of all-local testing followed by all-remote testing as a way of me not doing so.

> Currently our `metanorma-*` also trigger builds for `mn-samples-*` and `mn-templates-*` (was done in the scope of [metanorma/metanorma-cli#149](https://github.com/metanorma/metanorma-cli/issues/149)) but how useful this approach? Those build just triggers but I'm not sure if someone checks the status of those builds. This PR is just a "evolution" of this approach

I tuned them out a long time ago. Not least because of constant false alarms.

> > The only way forward is:
> > 
> > * Test each gem locally, because that's how I identify and propagate changes resulting from dependencies of gems.
> > * Compile each gem as I go locally. No releases.
> > * Hit some button to release all gems in the suite successively at the end
> > * Walk away, and wait for separate remote compilation the following day
> > * If any issues are identified in the process, fix, and re-hit the button.
> 
> According to my understanding, [metanorma/metanorma-release#21](https://github.com/metanorma/metanorma-release/issues/21) will be a such button. Probably the one difference is that it will do it in serial.
> 
> In case some issue happens (in the middle for example) this workflow it will fail. The fix needs to be applied, and workflow can be re-executed starting from failed gem and continued

Yeah, that's going to be pain, especially if the failure is a false alarm. Me actively monitoring this while at my day job the following day is an unreasonable request. This is at best an overnight glance.

> > And this will still prove unworkable, because GHA is monstrously unreliable, and fails for all sorts of reasons
> Nothing is perfect, unfortunately, let's see how it will works on small subset of gems

I'm hearing this a lot from people lately. There's a difference between "not perfect" and "completely useless", and the former does not license the latter. The only way to find out which applies is to try it. I can only repeat that, if GHA remains as unreliable as it has been, this is not going to work. I'm not going to wait for days instead of hours because GHA jobs become unavailable; and that's the risk this is introducing.

**Comment by opoudjis** [comment]
Ok, @CAMOBAP, I think we're now on the same page...

**Comment by CAMOBAP** [comment]
@opoudjis could you please ping me when it is safe to merge this release this PR (to not interfere with current release)

**Comment by CAMOBAP** [comment]
@opoudjis could you please ping me when it is safe to merge this release this PR (to not interfere with current release)

**Comment by opoudjis** [comment]
@CAMOBAP Safe to merge, though I'll let you do the merging.

**Comment by CAMOBAP** [comment]
This PR was just for testing, https://github.com/metanorma/ci/pull/105 - is merged

**Pull request closed without merging**
